server: server.c ../common/fifo.c register.c login.c logout.c userlist.c message.c
	gcc -o server server.c ../common/fifo.c register.c login.c logout.c userlist.c message.c -I/usr/include/mysql -L/usr/lib64/mysql -lmysqlclient
